import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import type { AgentPrompt } from './prompt-builder.js';
import { ALL_AGENTS } from './agent-definitions.js';

export class AgentWriter {
  /**
   * Writes agent definition files to .legacy-squad/agents/
   * These are read by the IDE (Claude Code, Codex, Cursor) as context.
   */
  async writeAgentDefinitions(outputDir: string): Promise<void> {
    const agentsDir = path.join(outputDir, 'agents');
    await mkdir(agentsDir, { recursive: true });

    for (const agent of ALL_AGENTS) {
      const content = [
        `# ${agent.name}`,
        '',
        `**Pillar:** ${agent.pillar}`,
        `**Role:** ${agent.role}`,
        '',
        '## Expertise',
        ...agent.expertise.map((e) => `- ${e}`),
        '',
        '## Reference Frameworks',
        ...agent.frameworks.map((f) => `- ${f}`),
        '',
        '## Instructions',
        '',
        agent.instructions,
        '',
        '## Expected Output Sections',
        ...agent.outputSections.map((s, i) => `${i + 1}. ${s}`),
      ].join('\n');

      await writeFile(path.join(agentsDir, `${agent.id}.md`), content, 'utf-8');
    }
  }

  /**
   * Writes ready-to-use prompts to .legacy-squad/prompts/
   * User copies these into their IDE to get AI-powered assessment.
   */
  async writePrompts(outputDir: string, prompts: AgentPrompt[]): Promise<void> {
    const promptsDir = path.join(outputDir, 'prompts');
    await mkdir(promptsDir, { recursive: true });

    for (const prompt of prompts) {
      const filename = `${prompt.agentId}-prompt.md`;
      await writeFile(path.join(promptsDir, filename), prompt.prompt, 'utf-8');
    }

    const indexContent = this.renderPromptIndex(prompts);
    await writeFile(path.join(promptsDir, 'README.md'), indexContent, 'utf-8');
  }

  private renderPromptIndex(prompts: AgentPrompt[]): string {
    const lines = [
      '# Legacy Squad — Agent Prompts',
      '',
      'These prompts were generated by the Legacy Squad Framework V1.',
      'Copy the content of any prompt file into your IDE (Claude Code, Codex, Cursor) to get an AI-powered assessment.',
      '',
      '## How to Use',
      '',
      '**Claude Code:**',
      '```',
      'cat .legacy-squad/prompts/security-agent-prompt.md | claude',
      '```',
      'Or paste the content directly into the Claude Code session.',
      '',
      '**Codex CLI:**',
      '```',
      'codex "$(cat .legacy-squad/prompts/security-agent-prompt.md)"',
      '```',
      '',
      '**Any IDE with AI:**',
      'Open the prompt file and paste its content into the AI chat.',
      '',
      '## Available Prompts',
      '',
      '| Agent | Pillar | Estimated Tokens | File |',
      '|-------|--------|------------------|------|',
    ];

    for (const p of prompts) {
      lines.push(`| ${p.agentName} | ${p.pillar} | ~${p.estimatedTokens} | \`${p.agentId}-prompt.md\` |`);
    }

    lines.push('');
    lines.push('## Workflow');
    lines.push('');
    lines.push('1. Run the Security Agent first (critical findings need immediate attention)');
    lines.push('2. Run Architecture Agent (structural understanding)');
    lines.push('3. Run Legacy Code Agent (quality assessment)');
    lines.push('4. Run Business Rules Agent (domain knowledge extraction)');
    lines.push('5. Run Modernization Agent last (synthesizes all other assessments)');
    lines.push('');
    lines.push('Each agent assessment can be saved to `.legacy-squad/outputs/assessments/` for the PRS consolidation step.');

    return lines.join('\n');
  }
}
