import type { ProviderPort } from '@legacy-squad/core';

export class MockProvider implements ProviderPort {
  readonly name = 'mock';

  async generate(prompt: string): Promise<string> {
    if (prompt.includes('executive_summary')) {
      return 'This legacy system requires attention to security, architecture, and code quality concerns identified through automated analysis.';
    }
    if (prompt.includes('recommended_next_steps')) {
      return '1. Address critical security findings immediately.\n2. Plan incremental TypeScript migration.\n3. Centralize API error handling.\n4. Establish test coverage baseline.';
    }
    return 'Analysis generated by Legacy Squad Framework V1 using automated compliance engine.';
  }
}
